app/views/student/forms.py
# -*- coding: utf-8 -*-
#coding=utf-8

app/views/student/__init__.py
# -*- coding: utf-8 -*-
#coding=utf-8

from flask import Blueprint

student = Blueprint('student', __name__)

from . import views

app/views/student/views.py
# -*- coding: utf-8 -*-
#coding=utf-8

from flask import render_template, redirect, request, url_for, flash, current_app, abort
from flask_login import login_required, current_user

from app import db
from app.decorators import student_required

from app.models.Arrange import Arrange, ArrangeTime
from app.models.Grades import Grades

from app.time import now_year, now_semaster

from . import student

# 管理已选课程
@student.route('/manager/selected')
@login_required
@student_required
def manager_selected():
    return render_template(
        'student/select_course_list.html',
        arranges=current_user.get_student().selected.all()
    )

# 显示可选课表
@student.route('/select/course')
@login_required
@student_required
def select_course_list():
    courses = []
    current_student = current_user.get_student()
    for arrange in Arrange.query.all():
        if arrange.year != now_year() or arrange.semaster != now_semaster():
            continue
        if arrange.department_id == current_student.department_id or arrange.course.nature == u'公共基础课':
            courses.append(arrange)
    return render_template(
        'student/select_course_list.html',
        arranges=courses
    )

# 选课
@student.route('/select/<int:id>')
@login_required
@student_required
def select_course(id):
    current_user.select_course(id)
    return redirect(url_for('student.select_course_list'))

# 退选
@student.route('/unselect/<int:id>')
@login_required
@student_required
def unselect_course(id):
    current_user.unselect_course(id)
    return redirect(url_for('student.select_course_list'))

# 查询课表
@student.route('/query/course/scedule')
@login_required
@student_required
def query_course_schedule():
    gtoi = {
        u"一": 1,
        u"二": 2,
        u"三": 3,
        u"四": 4,
        u"五": 5,
        u"六": 6,
        u"七": 7,
    }
    courses = current_user.get_student().selected.all()
    schedule = [ ['' for g in range(12)] for x in range(8)]
    for arrange in courses:
        # 去除不是本学期的课程
        if arrange.year != now_year() or arrange.semaster != now_semaster():
            continue
        for timespan in ArrangeTime.query.filter_by(id=arrange.id).all():
            name = timespan.timespan.name
            day, gid = gtoi[name[1]], int(name[4]) if not name[4:6].isdigit() else int(name[4:6])
            schedule[day][gid] = arrange.course.name + ' ' + arrange.place.name
    for i in range(1, 12):
        schedule[0][i] = u'第' + str(i) + u'节'
    return render_template(
        'student/course_schedule.html',
        schedule=schedule
    )

from app.other import grade_to_GPA

# 学期成绩
@student.route('/query/grade/semaster')
@login_required
@student_required
def query_grade_semaster():
    arranges = []
    # 总学分
    credit_sum = 0
    # 学分绩点总和
    credit_point_sum = 0
    # 未通过学分
    unpass_credit_sum = 0
    # 平均绩点
    gpa = 0
    for arrange in current_user.get_student().selected.all():
        if arrange.year == now_year() and arrange.semaster == now_semaster():
            grade = Grades.query.filter_by(student_id=current_user.id, arrange_id=arrange.id).first()
            if grade is None or grade.grade is None:
                continue
            grade = grade.grade
            arranges.append((arrange, grade, grade_to_GPA(grade)))
            credit_sum += arrange.course.credit
            credit_point_sum += arrange.course.credit * grade_to_GPA(grade)
            if grade < 60:
                unpass_credit_sum += arrange.course.credit
    if credit_sum == 0:
        gpa = 0
    else:
        gpa = credit_point_sum / credit_sum
    return render_template(
        'student/query_grade.html',
        arranges=arranges,
        credit_sum=credit_sum,
        credit_point_sum=credit_point_sum,
        unpass_credit_sum=unpass_credit_sum,
        gpa=gpa
    )


# 学年成绩
@student.route('/query/grade/year')
@login_required
@student_required
def query_grade_year():
    arranges = []
    # 总学分
    credit_sum = 0
    # 学分绩点总和
    credit_point_sum = 0
    # 未通过学分
    unpass_credit_sum = 0
    # 平均绩点
    gpa = 0
    for arrange in current_user.get_student().selected.all():
        if arrange.year == now_year():
            grade = Grades.query.filter_by(student_id=current_user.id, arrange_id=arrange.id).first()
            if grade is None or grade.grade is None:
                continue
            grade = grade.grade
            arranges.append((arrange, grade, grade_to_GPA(grade)))
            credit_sum += arrange.course.credit
            credit_point_sum += arrange.course.credit * grade_to_GPA(grade)
            if grade < 60:
                unpass_credit_sum += arrange.course.credit
    if credit_sum == 0:
        gpa = 0
    else:
        gpa = credit_point_sum / credit_sum
    return render_template(
        'student/query_grade.html',
        arranges=arranges,
        credit_sum=credit_sum,
        credit_point_sum=credit_point_sum,
        unpass_credit_sum=unpass_credit_sum,
        gpa=gpa
    )

# 历年成绩
@student.route('/query/grade/all')
@login_required
@student_required
def query_grade_all():
    arranges = []
    # 总学分
    credit_sum = 0
    # 学分绩点总和
    credit_point_sum = 0
    # 未通过学分
    unpass_credit_sum = 0
    # 平均绩点
    gpa = 0
    for arrange in current_user.get_student().selected.all():
        grade = Grades.query.filter_by(student_id=current_user.id, arrange_id=arrange.id).first()
        if grade is None or grade.grade is None:
            continue
        grade = grade.grade
        arranges.append((arrange, grade, grade_to_GPA(grade)))
        credit_sum += arrange.course.credit
        credit_point_sum += arrange.course.credit * grade_to_GPA(grade)
        if grade < 60:
            unpass_credit_sum += arrange.course.credit

    if credit_sum == 0:
        gpa = 0
    else:
        gpa = credit_point_sum / credit_sum
    return render_template(
        'student/query_grade.html',
        arranges=arranges,
        credit_sum=credit_sum,
        credit_point_sum=credit_point_sum,
        unpass_credit_sum=unpass_credit_sum,
        gpa=gpa
    )

app/templates/student/course_schedule.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 查看课表 {% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>学生课表</h1>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>节次</th>
                    <th>周一</th>
                    <th>周二</th>
                    <th>周三</th>
                    <th>周四</th>
                    <th>周五</th>
                    <th>周六</th>
                    <th>周日</th>
                </tr>
            </thead>
            <tbody>
                {% for i in range(1, 12) %}
                <tr>
                    <th scope="row">{{ schedule[0][i] }}</th>
                    {% for j in range(1, 8) %}
                    <td>{{ schedule[j][i] }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/student/navbar.html
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">选课管理<span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href="{{ url_for('student.manager_selected') }}">已选课程管理</a></li>
        <li><a href="{{ url_for('student.select_course_list') }}">学生选课</a></li>
    </ul>
</li>

<li><a href="{{ url_for('student.query_course_schedule') }}">课表查询</a></li>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">成绩查询<span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li>
            <a href="{{ url_for('student.query_grade_semaster') }}">
                本学期成绩
            </a>
        </li>
        <li>
            <a href="{{ url_for('student.query_grade_year') }}">
                本学年成绩
            </a>
        </li>
        <li>
            <a href="{{ url_for('student.query_grade_all') }}">
                所有成绩
            </a>
        </li>
    </ul>
</li>

app/templates/student/query_grade.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 成绩查询 {% endblock %}

{% block page_content %}
<h5 class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>成绩查询</h1>
        </div>
    </div>
    <div class="row">
        <span class="label label-primary">总学分：{{ credit_sum }}</span>
        <span class="label label-primary">学分绩点总和：{{ credit_point_sum }}</span>
        <span class="label label-primary">未通过学分：{{ unpass_credit_sum }}</span>
        <span class="label label-primary">平均学分绩点：{{ gpa }}</span>
    </div>
    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>学年学期</th>
                    <th>课程代码</th>
                    <th>课程名称</th>
                    <th>课程性质</th>
                    <th>学分</th>
                    <th>开课学院</th>
                    <th>成绩</th>
                    <th>绩点</th>
                </tr>
            </thead>
            <tbody>
                {% for arrange in arranges %}
                <tr>
                    <th scope="row">{{ arrange[0].year }}学年第{{ arrange[0].semaster }}学期</th>
                    <td>{{ arrange[0].course.code }}</td>
                    <td>{{ arrange[0].course.name }}</td>
                    <td>{{ arrange[0].course.nature }}</td>
                    <td>{{ arrange[0].course.credit }}</td>
                    <td>{{ arrange[0].department.name }}</td>
                    <td>{{ arrange[1] }}</td>
                    <td>{{ arrange[2] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/student/select_course_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 学生选课 {% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>可选课表</h1>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>学年学期</th>
                    <th>课程代码</th>
                    <th>课程名称</th>
                    <th>课程性质</th>
                    <th>学分</th>
                    <th>上课教师</th>
                    <th>上课地点</th>
                    <th>上课时间</th>
                    <th>开课学院</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                {% for arrange in arranges %}
                <tr>
                    <th scope="row">{{ arrange.year }}学年第{{ arrange.semaster }}学期</th>
                    <td>{{ arrange.course.code }}</td>
                    <td>{{ arrange.course.name }}</td>
                    <td>{{ arrange.course.nature }}</td>
                    <td>{{ arrange.course.credit }}</td>
                    <td>{{ arrange.teacher.get_teacher().name }}</td>
                    <td>{{ arrange.place.name }}</td>
                    <td>{{ arrange.get_timespan() }}</td>
                    <td>{{ arrange.department.name }}</td>
                    <td>
                        {% if not current_user.is_selected(arrange.id) %}
                        <a href="{{ url_for('student.select_course', id=arrange.id) }}">选课</a>
                        {% else %}
                        <a href="{{ url_for('student.unselect_course', id=arrange.id) }}">退选</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}