app/views/teacher/forms.py
# -*- coding: utf-8 -*-
#coding=utf-8

app/views/teacher/__init__.py
# -*- coding: utf-8 -*-
#coding=utf-8

from flask import Blueprint

teacher = Blueprint('teacher', __name__)

from . import views

app/views/teacher/views.py
# -*- coding: utf-8 -*-
#coding=utf-8

from flask import render_template, redirect, request, url_for, flash, current_app, abort
from flask_login import login_required, current_user

from app import db
from app.decorators import teacher_required
from app.models.Arrange import Arrange, ArrangeTime
from app.models.User import User, StudentUser, TeacherUser
from app.models.Grades import Grades

from app.time import now_semaster, now_year

from . import teacher

# 授课信息查询
@teacher.route('/query/course/arrange')
@login_required
@teacher_required
def query_course_arrange():
    gtoi = {
        u"一": 1,
        u"二": 2,
        u"三": 3,
        u"四": 4,
        u"五": 5,
        u"六": 6,
        u"七": 7,
    }
    courses = current_user.get_teacher().arranges.all()
    schedule = [ ['' for g in range(12)] for x in range(8) ]
    for arrange in courses:
        # 去除不是本学期的课程
        if arrange.year != now_year() or arrange.semaster != now_semaster():
            continue
        for timespan in ArrangeTime.query.filter_by(id=arrange.id).all():
            name = timespan.timespan.name
            day, gid = gtoi[name[1]], int(name[4]) if not name[4:6].isdigit() else int(name[4:6])
            schedule[day][gid] = arrange.course.name + ' ' + arrange.place.name
    for i in range(1, 12):
        schedule[0][i] = u'第' + str(i) + u'节'
    return render_template(
        'teacher/course_schedule.html',
        schedule=schedule
    )

# 点名册查询
@teacher.route('/query/course/student/list')
@login_required
@teacher_required
def query_course_student_list():
    arranges = []
    for arrange in current_user.get_teacher().arranges.all():
        # 去除不是本学期的课程
        if arrange.year != now_year() or arrange.semaster != now_semaster():
            continue
        arranges.append(arrange)

    return render_template(
        'teacher/course_student_list_index.html',
        arranges=arranges
    )

@teacher.route('/query/course/stduent/<int:id>')
@login_required
@teacher_required
def query_course_student(id):
    arrange = Arrange.query.filter_by(id=id).first()
    if arrange.teacher_id != current_user.id:
        return abort(403)
    students = []
    for s in arrange.student:
        students.append((User.query.filter_by(id=s.id).first().username, s))
    return render_template(
        'teacher/course_student_list.html',
        students=students,
        course_name=arrange.course.name
    )

# 教学班成绩查询
@teacher.route('/query/course/grade')
@login_required
@teacher_required
def query_course_grade_list():
    arranges = []
    for arrange in current_user.get_teacher().arranges.all():
        # 去除不是本学期的课程
        if arrange.year != now_year() or arrange.semaster != now_semaster():
            continue
        arranges.append(arrange)

    return render_template(
        'teacher/query_course_grade_index.html',
        arranges=arranges
    )

@teacher.route('/query/course/grade/<int:id>')
@login_required
@teacher_required
def query_course_grade(id):
    arrange = Arrange.query.filter_by(id=id).first()
    if arrange.teacher_id != current_user.id:
        return abort(403)
    students = []
    for s in arrange.student:
        score = Grades.query.filter_by(arrange_id=arrange.id, student_id=s.id).first()
        if score is None or score.grade is None:
            score = ''
        else:
            score = score.grade
        students.append((User.query.filter_by(id=s.id).first().username, s, score))
    return render_template(
        'teacher/query_course_grade.html',
        arrange_id=arrange.id,
        students=students,
        course_name=arrange.course.name
    )


# 成绩录入
@teacher.route('/input/course/grade')
@login_required
@teacher_required
def input_course_grade_list():
    arranges = []
    for arrange in current_user.get_teacher().arranges.all():
        # 去除不是本学期的课程
        if arrange.year != now_year() or arrange.semaster != now_semaster():
            continue
        arranges.append(arrange)

    return render_template(
        'teacher/input_course_grade_index.html',
        arranges=arranges
    )

@teacher.route('/input/course/grade/<int:id>', methods=['GET', 'POST'])
@login_required
@teacher_required
def input_course_grade(id):
    arrange = Arrange.query.filter_by(id=id).first()
    if arrange.teacher_id != current_user.id:
        return abort(403)
    students = []
    for s in arrange.student:
        score = Grades.query.filter_by(arrange_id=arrange.id, student_id=s.id).first()
        if score is None or score.grade is None:
            score = ''
        else:
            score = score.grade
        students.append((User.query.filter_by(id=s.id).first().username, s, score))
    return render_template(
        'teacher/input_course_grade.html',
        arrange_id=arrange.id,
        students=students,
        course_name=arrange.course.name
    )

@teacher.route('/input/course/grade/<int:sid>/<int:aid>/', methods=['GET', 'POST'])
@login_required
@teacher_required
def add_grade(aid, sid):
    score = Grades.query.filter_by(arrange_id=aid, student_id=sid).first()
    rgrade = request.args.get('grade')
    if score is None:
        score = Grades(
            arrange_id=aid,
            student_id=sid,
            grade=rgrade
        )
    else:
        score.grade = rgrade

    db.session.add(score)
    db.session.commit()
    return redirect(url_for('teacher.input_course_grade', id=aid))

app/templates/teacher/course_schedule.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 查看课表 {% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>授课信息表</h1>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>节次</th>
                    <th>周一</th>
                    <th>周二</th>
                    <th>周三</th>
                    <th>周四</th>
                    <th>周五</th>
                    <th>周六</th>
                    <th>周日</th>
                </tr>
            </thead>
            <tbody>
                {% for i in range(1, 12) %}
                <tr>
                    <th scope="row">{{ schedule[0][i] }}</th>
                    {% for j in range(1, 8) %}
                    <td>{{ schedule[j][i] }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/teacher/course_student_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 点名册查询 {% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>点名册</h1>
        </div>
    </div>
    <div class="row">
        <h4>当前课程：{{ course_name }}</h4>
    </div>
    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>学号</th>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>院系</th>
                    <th>专业</th>
                    <th>班级</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <th scope="row">{{ student[0] }}</th>
                    <td>{{ student[1].name }}</td>
                    <td>{{ student[1].sex }}</td>
                    <td>{{ student[1].department.name }}</td>
                    <td>{{ student[1].major.name }}</td>
                    <td>{{ student[1].rclass.name }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/teacher/course_student_list_index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 点名册查询 {% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>点名册查询</h1>
        </div>
    </div>
    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>学年学期</th>
                    <th>课程代码</th>
                    <th>课程名称</th>
                    <th>课程性质</th>
                    <th>学分</th>
                    <th>上课地点</th>
                    <th>上课时间</th>
                    <th>开课学院</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                {% for arrange in arranges %}
                <tr>
                    <th scope="row">{{ arrange.year }}学年第{{ arrange.semaster }}学期</th>
                    <td>{{ arrange.course.code }}</td>
                    <td>{{ arrange.course.name }}</td>
                    <td>{{ arrange.course.nature }}</td>
                    <td>{{ arrange.course.credit }}</td>
                    <td>{{ arrange.place.name }}</td>
                    <td>{{ arrange.get_timespan() }}</td>
                    <td>{{ arrange.department.name }}</td>
                    <td>
                        <a href="{{ url_for('teacher.query_course_student', id=arrange.id) }}">查看点名册</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/teacher/input_course_grade.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 成绩录入 {% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>成绩录入</h1>
        </div>
    </div>
    <div class="row">
        <h4>当前课程：{{ course_name }}</h4>
    </div>
    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>学号</th>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>院系</th>
                    <th>专业</th>
                    <th>班级</th>
                    <th>成绩</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <th scope="row">{{ student[0] }}</th>
                    <td>{{ student[1].name }}</td>
                    <td>{{ student[1].sex }}</td>
                    <td>{{ student[1].department.name }}</td>
                    <td>{{ student[1].major.name }}</td>
                    <td>{{ student[1].rclass.name }}</td>
                    <td>
                        <form name="input" action="{{ url_for('teacher.add_grade', sid=student[1].id, aid=arrange_id) }}" method="get">
                            分数:
                        <input type="text" name="grade" value="{{ student[2] }}"/>
                        <input type="submit" value="提交" />
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/teacher/input_course_grade_index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 成绩录入 {% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>成绩录入</h1>
        </div>
    </div>
    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>学年学期</th>
                    <th>课程代码</th>
                    <th>课程名称</th>
                    <th>课程性质</th>
                    <th>学分</th>
                    <th>上课地点</th>
                    <th>上课时间</th>
                    <th>开课学院</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                {% for arrange in arranges %}
                <tr>
                    <th scope="row">{{ arrange.year }}学年第{{ arrange.semaster }}学期</th>
                    <td>{{ arrange.course.code }}</td>
                    <td>{{ arrange.course.name }}</td>
                    <td>{{ arrange.course.nature }}</td>
                    <td>{{ arrange.course.credit }}</td>
                    <td>{{ arrange.place.name }}</td>
                    <td>{{ arrange.get_timespan() }}</td>
                    <td>{{ arrange.department.name }}</td>
                    <td>
                        <a href="{{ url_for('teacher.input_course_grade', id=arrange.id) }}">成绩录入</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/teacher/navbar.html
<li><a href="{{ url_for('teacher.query_course_arrange') }}">授课信息查询</a></li>

<li><a href="{{ url_for('teacher.query_course_student_list') }}">点名册查询</a></li>

<li><a href="{{ url_for('teacher.query_course_grade_list') }}">教学班成绩查询</a></li>

<li><a href="{{ url_for('teacher.input_course_grade_list') }}">成绩录入</a></li>

app/templates/teacher/query_course_grade.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 教学班成绩查询 {% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>教学班成绩查询</h1>
        </div>
    </div>
    <div class="row">
        <h4>当前课程：{{ course_name }}</h4>
    </div>
    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>学号</th>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>院系</th>
                    <th>专业</th>
                    <th>班级</th>
                    <th>成绩</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <th scope="row">{{ student[0] }}</th>
                    <td>{{ student[1].name }}</td>
                    <td>{{ student[1].sex }}</td>
                    <td>{{ student[1].department.name }}</td>
                    <td>{{ student[1].major.name }}</td>
                    <td>{{ student[1].rclass.name }}</td>
                    <td>{{ student[2] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/teacher/query_course_grade_index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 成绩查询 {% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>教学班成绩查询</h1>
        </div>
    </div>
    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>学年学期</th>
                    <th>课程代码</th>
                    <th>课程名称</th>
                    <th>课程性质</th>
                    <th>学分</th>
                    <th>上课地点</th>
                    <th>上课时间</th>
                    <th>开课学院</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                {% for arrange in arranges %}
                <tr>
                    <th scope="row">{{ arrange.year }}学年第{{ arrange.semaster }}学期</th>
                    <td>{{ arrange.course.code }}</td>
                    <td>{{ arrange.course.name }}</td>
                    <td>{{ arrange.course.nature }}</td>
                    <td>{{ arrange.course.credit }}</td>
                    <td>{{ arrange.place.name }}</td>
                    <td>{{ arrange.get_timespan() }}</td>
                    <td>{{ arrange.department.name }}</td>
                    <td>
                        <a href="{{ url_for('teacher.query_course_grade', id=arrange.id) }}">成绩单查看</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}