app/models/Department.py
# -*- coding: utf-8 -*-
#coding=utf-8

from app import db

class Department(db.Model):
    __tablename__ = 'departments'

    # 编号
    id = db.Column(db.Integer, primary_key=True)
    # 院系名称
    name = db.Column(db.String(64), nullable=False, unique=True)

    # 下属专业
    majors = db.relationship('Major', backref='department', lazy='dynamic')
    # 学生
    students = db.relationship('StudentUser', backref='department', lazy='dynamic')
    # 下属教师
    teachers = db.relationship('TeacherUser', backref='department', lazy='dynamic')
    # 院系管理员
    managers = db.relationship('DepartmentUser', backref='department', lazy='dynamic')
    # 下属课程
    courses = db.relationship('Course', backref='department', lazy='dynamic')
    # 下属课程安排
    arranges = db.relationship('Arrange', backref='department', lazy='dynamic')

    def __repr__(self):
        return '<Department: %r>' % self.name


def get_departments_choices_list():
    return [(dep.id, dep.name) for dep in Department.query.all()]

app/views/department/forms.py
# -*- coding: utf-8 -*-
#coding=utf-8

from flask import current_app
from flask_wtf import Form
from wtforms import StringField, SubmitField, TextAreaField,\
    SelectField, FloatField, IntegerField, Label
from wtforms.validators import DataRequired, Length, NumberRange

from app.time import now_semaster, now_year
from app.models.Course import Course
from app.models.User import TeacherUser
from app.models.Place import Place
from app.models.TimeSpan import TimeSpan
from app.models.Arrange import Arrange, ArrangeTime

# 公告编辑表单
class PostForm(Form):
    title = StringField(u'公告标题', validators=[DataRequired(), Length(min=1, max=256)])
    body = TextAreaField(u'公告内容')
    submit = SubmitField(u'提交')

# 课程表单
class CourseForm(Form):
    code = StringField(u'课程代码', validators=[DataRequired(), Length(min=1, max=16)])
    name = StringField(u'课程名称', validators=[DataRequired(), Length(min=1, max=64)])
    nature = SelectField(u'课程性质', validators=[DataRequired()])
    credit = FloatField(u'学分', validators=[DataRequired()])
    description = TextAreaField(u'课程描述')
    submit = SubmitField(u'提交')

    # 设置课程性质选项
    def set_choices(self):
        self.nature.choices = current_app.config['COURSE_NATURE']


# 添加本学期课程安排
class ArrangeForm(Form):
    year = IntegerField(u'学年', validators=[DataRequired(), NumberRange(min=2000, max=2100)])
    semaster = IntegerField(u'学期', validators=[DataRequired(), NumberRange(min=1, max=3)])
    course = SelectField(u'课程', validators=[DataRequired()], coerce=int)
    teacher = SelectField(u'授课教师', validators=[DataRequired()], coerce=int)
    place = SelectField(u'上课地点', validators=[DataRequired()], coerce=int)
    all_timespan = []

    submit = SubmitField(u'添加课程安排')

    def set_choices(self, department_id):
        self.course.choices = \
            [(x.id, x.name) for x in Course.query.filter_by(department_id=department_id).all()]
        self.teacher.choices = \
            [(x.id, x.name) for x in TeacherUser.query.filter_by(department_id=department_id).all()]
        self.place.choices = \
            [(x.id, x.name) for x in Place.query.all()]

        self.year.data = now_year()
        self.semaster.data = now_semaster()


class ArrangeTimeSpanForm(Form):
    timespan = SelectField(u'上课时间', coerce=int)
    submit = SubmitField(u'添加时间')

    def set_choices(self, arrange_id):
        arrange = Arrange.query.filter_by(id=arrange_id).first()

        year = arrange.year
        semaster = arrange.semaster
        place_id = arrange.place_id

        occur_arranges = Arrange.query.filter_by(place_id=place_id).all()
        occur = []

        for occur_arrange in occur_arranges:
            for p in ArrangeTime.query.filter_by(id=occur_arrange.id).all():
                occur.append(p.timespan_id)

        all_time = [(x.id, x.name) for x in TimeSpan.query.all()]
        res = []
        for i in all_time:
            if i[0] not in occur:
                res.append(i)
        self.timespan.choices = res

app/views/department/__init__.py
# -*- coding: utf-8 -*-
#coding=utf-8

from flask import Blueprint

department = Blueprint('department', __name__)

from . import views

app/views/department/views.py
# -*- coding: utf-8 -*-
#coding=utf-8

from flask import render_template, redirect, request, url_for, flash, current_app, abort
from flask_login import login_required, current_user

from app import db
from app.decorators import department_required
from app.models.Role import Permission
from app.models.Post import Post
from app.models.Course import Course
from app.models.User import DepartmentUser
from app.models.Arrange import Arrange, ArrangeTime

from datetime import datetime

from . import department
from .forms import PostForm, CourseForm, ArrangeForm, ArrangeTimeSpanForm

# 发布公告
@department.route('/post/add', methods=['GET', 'POST'])
@login_required
@department_required
def post():
    form = PostForm()
    if current_user.username != current_app.config['ADMIN'] and form.validate_on_submit():
        post = Post(
            body=form.body.data,
            author_id=current_user.id,
            title=form.title.data,
            post_time=datetime.utcnow()
        )
        db.session.add(post)
        db.session.commit()
        return redirect(request.args.get('next') or url_for('main.index'))
    return render_template(
        'department/post_add.html',
        form=form
    )

# 查看公告列表，或者删除公告
@department.route('/post/list', methods=['GET'])
@login_required
@department_required
def post_list():
    return render_template(
        'department/post_list.html',
        posts=Post.query.filter_by(author_id=current_user.id).order_by(Post.post_time.desc()).all()
    )

# 删除公告
@department.route('/post/del/<int:id>', methods=['GET'])
@login_required
@department_required
def del_post(id):
    post = Post.query.filter_by(id=id).first()
    if post:
        db.session.delete(post)
        db.session.commit()
        flash(u'删除成功')
    else:
        flash(u'删除失败，公告已经不存在了')
    return redirect(
        url_for('department.post_list')
    )

# 编辑公告
@department.route('/post/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@department_required
def edit_post(id):
    form = PostForm()
    post = Post.query.filter_by(id=id).first()
    if post is None:
        return abort(404)
    if form.validate_on_submit():
        post.body = form.body.data
        post.title = form.title.data
        post.post_time = datetime.utcnow()
        db.session.add(post)
        db.session.commit()
        flash(u'公告已经成功更改')
        return redirect(url_for('department.post_list'))
    form.body.data = post.body
    form.title.data = post.title
    return render_template(
        'department/post_edit.html',
        form=form
    )

# 添加课程
@department.route('/course/add', methods=['GET', 'POST'])
@login_required
@department_required
def add_course():
    form = CourseForm()
    form.set_choices()
    department_id = DepartmentUser.query.filter_by(id=current_user.id).first().department_id
    if form.validate_on_submit():
        course = Course(
            code=form.code.data,
            name=form.name.data,
            nature=form.nature.data,
            credit=form.credit.data,
            department_id=department_id,
            description=form.description.data
        )
        db.session.add(course)
        db.session.commit()
        flash(u'添加课程成功')
        return redirect(request.args.get('next') or url_for('department.list_course'))
    return render_template('department/add_course.html', form=form)

# 显示课程列表
@department.route('/course/list', methods=['GET'])
@login_required
@department_required
def list_course():
    department_id = DepartmentUser.query.filter_by(id=current_user.id).first().department_id
    courses = Course.query.filter_by(department_id=department_id).all()
    return render_template(
        'department/list_course.html', courses=courses
    )

# 编辑课程
@department.route('/course/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@department_required
def edit_course(id):
    form = CourseForm()
    form.set_choices()
    course = Course.query.filter_by(id=id).first()
    if course is None:
        return abort(404)
    if form.validate_on_submit():
        course.code = form.code.data
        course.name = form.name.data
        course.nature = form.nature.data
        course.credit = form.credit.data
        course.description = form.description.data
        db.session.add(course)
        db.session.commit()
        flash(u'修改课程成功')
        return redirect(url_for('department.list_course'))
    form.code.data = course.code
    form.name.data = course.name
    form.nature.data = course.nature
    form.credit.data = course.credit
    form.description = course.description
    return render_template('department/edit_course.html', form=form)

# 删除课程
@department.route('course/del/<int:id>', methods=['GET', 'POST'])
@login_required
@department_required
def del_course(id):
    course = Course.query.filter_by(id=id).first()
    if course is None:
        return abort(404)
    db.session.delete(course)
    db.session.commit()
    return redirect(url_for('department.list_course'))


# 安排课程
@department.route('course/arrange', methods=['GET', 'POST'])
@login_required
@department_required
def arrange_course():
    nowdep = DepartmentUser.query.filter_by(id=current_user.id).first()
    form = ArrangeForm()
    form.set_choices(nowdep.department.id)
    if form.validate_on_submit():
        arrange = Arrange(
            year=form.year.data,
            semaster=form.semaster.data,
            course_id=form.course.data,
            teacher_id=form.teacher.data,
            place_id=form.place.data,
            department_id=nowdep.department.id
        )
        db.session.add(arrange)
        db.session.commit()
        flash(u'你已经成功添加了一门课程安排，请为其安排上课时间')
        return redirect(url_for('department.arrange_course_timespan', arrange_id=arrange.id))
    return render_template('department/arrange_course.html', form=form)

# 安排课程时间
@department.route('course/arrange_time/<int:arrange_id>', methods=['GET', 'POST'])
@login_required
@department_required
def arrange_course_timespan(arrange_id):
    form = ArrangeTimeSpanForm()
    form.set_choices(arrange_id=arrange_id)
    if form.validate_on_submit():
        arrange_time = ArrangeTime(
            id = arrange_id,
            timespan_id=form.timespan.data
        )
        db.session.add(arrange_time)
        db.session.commit()
    choosed = ArrangeTime.query.filter_by(id=arrange_id).all()
    return render_template(
        'department/arrange_course_time.html',
        form=form,
        choosed=choosed)

# 删除课程安排时间
@department.route('course/arrange_time/del/<int:arrange_id>/<int:timespan_id>')
@login_required
@department_required
def del_course_timespan(arrange_id, timespan_id):
    result = ArrangeTime.query.filter_by(id=arrange_id, timespan_id=timespan_id).first()
    if result:
        db.session.delete(result)
        db.session.commit()
    return redirect(url_for('department.arrange_course_timespan', arrange_id=arrange_id))

# 显示课程安排列表
@department.route('course/arrange/list', methods=['GET', 'POST'])
@login_required
@department_required
def arrange_list():
    current_department = DepartmentUser.query.filter_by(id=current_user.id).first().department
    arranges = Arrange.query.filter_by(department=current_department).order_by(Arrange.year.desc()).all()
    return render_template(
        'department/arrange_list.html',
        arranges=arranges
    )

# 删除课程安排
@department.route('course/arrange/del/<int:id>', methods=['GET'])
@login_required
@department_required
def del_arrange(id):
    arrange = Arrange.query.filter_by(id=id).first()
    if arrange is not None:
        db.session.delete(arrange)
        db.session.commit()
    return redirect(url_for('department.arrange_list'))

app/templates/department/add_course.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 公告编辑 {% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>添加课程</h1>
</div>

<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/department/arrange_course.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 公告编辑 {% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>创建课程安排</h1>
</div>

<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/department/arrange_course_time.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 公告编辑 {% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>给课程安排添加上课时间</h1>
</div>

<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
<div class="row">
    <h4>管理已经添加的时间</h4>
    <table class="table">
        <thead>
            <tr>
                <th>课程时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        {% for val in choosed %}
        <tr>
            <th scope="row">{{ val.timespan.name }}</th>
            <td>
                <a href="{{ url_for('department.del_course_timespan', arrange_id=val.id, timespan_id=val.timespan_id) }}">
                    删除
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

app/templates/department/arrange_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 本院课程 {% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>本院课程</h1>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>学年学期</th>
                    <th>课程代码</th>
                    <th>课程名称</th>
                    <th>上课教师</th>
                    <th>上课地点</th>
                    <th>上课时间</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                {% for arrange in arranges %}
                    <th scope="row">{{ arrange.year }}学年第{{ arrange.semaster }}学期</th>
                    <td>{{ arrange.course.code }}</td>
                    <td>{{ arrange.course.name }}</td>
                    <td>{{ arrange.teacher.get_teacher().name }}</td>
                    <td>{{ arrange.place.name }}</td>
                    <td>{{ arrange.timespan.name }}</td>
                    <td>
                        <a href="{{ url_for('department.arrange_course_timespan', year=arrange.year, semaster=arrange.semaster, course_id=arrange.course.id, teacher_id=arrange.teacher.id, place_id=arrange.place.id) }}">添加时间</a>
                        <a href="{{ url_for('department.del_arrange', id=arrange.id) }}">删除</a>
                    </td>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/department/edit_course.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 公告编辑 {% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>编辑课程</h1>
</div>

<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/department/list_course.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 本院课程 {% endblock %}

{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>本院课程</h1>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>课程代码</th>
                    <th>课程名称</th>
                    <th>课程性质</th>
                    <th>学分</th>
                    <th>开课学院</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}
                <tr>
                    <th scope="row">{{ course.code }}</th>
                    <td>{{ course.name }}</td>
                    <td>{{ course.nature }}</td>
                    <td>{{ course.credit }}</td>
                    <td>{{ course.department.name }}</td>
                    <td>
                        <a href="{{ url_for('department.edit_course', id=course.id) }}">编辑</a>
                        <a href="{{ url_for('department.del_course', id=course.id) }}">删除</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/department/navbar.html
<li><a href="{{ url_for('admin.add_major') }}">专业管理</a></li>

<li><a href="{{ url_for('admin.add_class') }}">班级管理</a></li>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">公告管理<span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href="{{ url_for('department.post') }}">发布公告</a></li>
        <li><a href="{{ url_for('department.post_list') }}">公告列表</a></li>
    </ul>
</li>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">课程管理<span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href="{{ url_for('department.add_course') }}">添加课程</a></li>
        <li><a href="{{ url_for('department.list_course') }}">课程列表</a></li>
    </ul>
</li>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">课程安排<span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href="{{ url_for('department.arrange_course') }}">添加新的课程安排</a></li>
        <li><a href="{{ url_for('department.arrange_list') }}">课程安排列表</a></li>
    </ul>
</li>

app/templates/department/post_add.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 添加公告 {% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>添加公告</h1>
</div>

<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/department/post_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 公告编辑 {% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>编辑公告</h1>
</div>

<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/department/post_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 教务管理系统 - 我的公告 {% endblock %}

{% block page_content %}
<ul class="posts">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1>我的公告</h1>
        </div>
    </div>
    {% for post in posts %}
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="thumbnail">
            <div class="caption">
                <h3>{{ post.title }}</h3>
                <p>发布者：{{ post.get_author_name() }}</p>
                <p>发布时间：{{ moment(post.post_time).format('MMMM Do YYYY, h:mm:ss a') }}</p>
                <p>{{ post.body }}</p>
                <p>
                    <a href="{{ url_for('department.edit_post', id=post.id) }}" class="btn btn-primary" role="button">编辑</a>
                    <a href="{{ url_for('department.del_post', id=post.id) }}" class="btn btn-danger" role="button">删除</a>
                </p>
            </div>
            </div>
        </div>
    </div>
    {% endfor %}
</ul>

{% endblock %}